### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by vcardins** [PowerOfM/eda-challenge#1]
Hello Mesbah, I'm reviewing your assignment and I'm facing issues starting the application. Please, have a look at the attached screenshot. Thoughts?
![image](https://github.com/PowerOfM/eda-challenge/assets/2383329/a06b398e-c42d-47e3-856e-120dcdc327c5)

**Comment by vcardins** [comment]
> Hello Mesbah, I'm reviewing your assignment and I'm facing issues starting the application. Please, have a look at the attached screenshot. Thoughts? ![image](https://user-images.githubusercontent.com/2383329/238748761-a06b398e-c42d-47e3-856e-120dcdc327c5.png)

After cleaning up the npm cache and reinstalling it, I was able to run it. All doo now!
Best of luck, man!!

**Comment by PowerOfM** [comment]
Thank you! Glad you were able to get it working!
